spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/sgg_hibernate?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
      username: py
      password: 123
  jpa:
    hibernate:
      ddl-auto: none